name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Cache Nx
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: nx-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/project.json', '**/nx.json') }}
          restore-keys: |
            nx-${{ runner.os }}-

      # Lint / Test / Build only what changed
      - name: Lint (affected)
        run: npx nx affected -t lint --parallel=3

      - name: Unit tests (affected)
        run: npx nx affected -t test --ci --code-coverage --parallel=3

      - name: Build (affected, prod)
        run: npx nx affected -t build --configuration=production --parallel=3

      # E2E for shell only (adjust if you have multiple e2e projects)
      - name: E2E (shell)
        run: npx nx e2e shell-e2e --ci
        # If you generated e2e for remotes too, add extra steps or use affected -t e2e

      # Optional: upload dist artifacts for changed apps
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
